### ISSUE TITLE
SSR客户端连接失败，修改参数502

### ISSUE THREAD

**Issue by smusicsanshu** [FunctionClub/SWEB#1]
**【vultr】Debian 7 x64 (wheezy)    安装过程顺利  。**

- 只出现一条提示：WARNING: timestamping does nothing in combination with -O. See the manual
                                for details.
- 但是结尾提示：Install Finished!
                            Visit http://your ip to Enjoy!
- 登录WEB成功，SSR客户端（WIN10）帐号连接失败.
- 在WEB提交 修改的 端口和密码时   502 Bad Gateway。

**Comment by smusicsanshu** [comment]
**【vultr】Debian 8 x64  安装过程顺利 。**

- 登录WEB成功
- SSR客户端（WIN10）链接成功。
- 在WEB提交 修改的 端口和密码时 **502 Bad Gateway**

**Comment by YLWS-4617** [comment]
已解决。
