### ISSUE TITLE
Errot，客户端能连接上服务器，但是不能上网， [Errno 97] 

### ISSUE THREAD

**Issue by DavidYaonanZhu** [FunctionClub/SWEB#2]
系统运行记录报错：
shell.py:50 [Errno 97] Address family not supported by protocol
不知道该怎么解决，我用的是阿里云服务器，Centos6.8

**Comment by YLWS-4617** [comment]
给我看下你的配置信息

**Comment by DavidYaonanZhu** [comment]
问题解决了。
我用的阿里云服务器，服务器禁止了一些端口，在设定里把要用到的端口都开放开了，就可以了。
